sygmaprotocol/explorer-ui

.github/ISSUE_TEMPLATE/backlog-item.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request-or-epic.md, .github/pull_request_template.md, .github/workflows/deploy_ecs-explorer-ui_STAGE.yaml, .github/workflows/docker-build-and-push.yml, .github/workflows/release.yml
- added github folder
- issue templates
- workflows
=> feat: github folder

.github/workflows/pr.yaml
- Adds semantic workflow for the Prs
=> chore: Workflow for semantic revision

src/pages/ExplorerPage/ExplorerPage.tsx, src/pages/ExplorerPage/reducer.ts
This PR:
- adds funtionality to the page buttons
- moves state logic to reducer
Closes: #10
=> feat: pagination logic and buttons enabled

.github/workflows/cf-deploy-prod.yml, .github/workflows/cf-deploy-test.yml
=> fix: update explorer api urls

.github/workflows/cf-deploy-prod.yml, .github/workflows/cf-deploy-test.yml
=> chore: add shared config url

src/utils/Helpers.tsx
This PR adjust helper to show mins if tx is under an hour
Closes: #66
=> feat: showing mins if tx is under hour

.github/workflows/cf-deploy-test.yml, README.md
- fix env var on test workflow file
=> fix: fix env name

package.json, src/utils/Helpers.tsx, yarn.lock
=> fix: fixing date issue

src/components/ExplorerTable/ExplorerTable.tsx, src/pages/DetailView/DetailView.tsx, src/pages/ExplorerPage/reducer.ts, src/utils/Helpers.tsx
If the usd value is zero, it doesn't render. Also, a minor fix on decimals
Closes: #87 #85
=> chore: hide usd value if it is zero

src/utils/Helpers.tsx
- fix render for cronos and base logos for mainnet
Closes: #91
=> chore: adding chain ids for Base and Cronos mainnet

src/utils/Helpers.tsx
Add network IDs for Base and Cronos to the network name-resolving helper function.
=> fix: wrong network name

src/components/ExplorerTable/ExplorerTable.tsx, src/pages/DetailView/DetailView.tsx, src/utils/Helpers.test.ts, src/utils/Helpers.tsx
Misc fixes and moving some logic to helpers
=> feat: misc fixes

.github/workflows/cf-deploy-prod.yml, src/pages/DetailView/DetailView.tsx, src/pages/ExplorerPage/ExplorerPage.tsx, src/utils/Helpers.tsx
=> chore: explorer urls for prod and formating links for source and destination tx hash

.github/workflows/cf-deploy-test.yml
=> fix: minor fix for testnet UI

src/components/ExplorerTable/ExplorerTable.tsx, src/pages/DetailView/DetailView.tsx, src/types/explorer.ts
Fixes issues with render of dates
Closes: #114
=> fix: fix render of dates

src/pages/DetailView/DetailView.tsx
=> chore: fix explorer urls

src/utils/Helpers.tsx
This PR fix render for icon and name of new testnets
=> fix: render name and icon for new testnets

src/App.tsx, src/pages/ExplorerPage/ExplorerPage.tsx
Message to display that Rhala is currently not available
=> chore: message for rhala

src/utils/Helpers.tsx
- Remove fixed value of fee for correct wording
Closes: #128
=> fix: remove fixed amount on fee for no fee wording

src/utils/Helpers.tsx
if domain is substrate 50 PHA displayed
Closes: #130
=> fix: fees if domain is substrate

src/utils/Helpers.test.ts, src/utils/Helpers.tsx
This PR fixes bug with dates after 30 days
Closes: #139
=> fix: refactor dates logic

src/utils/Helpers.tsx
=> chore: remove log

src/components/ExplorerTable/ExplorerTable.tsx, src/pages/DetailView/DetailView.tsx
=> fix: transform old pending status into failed

src/utils/renderUtils.tsx
=> fix: B3 mainnet icon
